server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/userfc/ {
        proxy_pass http://userfc:28080/;
    }

    location /api/productfc/ {
        proxy_pass http://productfc:28081/;
    }

    location /api/orderfc/ {
        proxy_pass http://orderfc:28082/;
    }

    location /api/paymentfc/ {
        proxy_pass http://paymentfc:28083/;
    }
}
