version: "3.8"

services:
  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:15
    container_name: go-commerce-postgres
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - go-commerce-network
    restart: unless-stopped

  # Redis 캐시
  redis:
    image: redis:7-alpine
    container_name: go-commerce-redis
    command: redis-server --requirepass admin
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - go-commerce-network
    restart: unless-stopped

  # USERFC 서비스
  userfc:
    image: your-registry.com/go-commerce-userfc:latest
    container_name: go-commerce-userfc
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=user
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=admin
    depends_on:
      - postgres
      - redis
    networks:
      - go-commerce-network
    restart: unless-stopped

  # ORDERFC 서비스
  orderfc:
    image: your-registry.com/go-commerce-orderfc:latest
    container_name: go-commerce-orderfc
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=user
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=admin
    depends_on:
      - postgres
      - redis
    networks:
      - go-commerce-network
    restart: unless-stopped

  # PRODUCTFC 서비스
  productfc:
    image: your-registry.com/go-commerce-productfc:latest
    container_name: go-commerce-productfc
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=user
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=admin
    depends_on:
      - postgres
      - redis
    networks:
      - go-commerce-network
    restart: unless-stopped

  # PAYMENTFC 서비스
  paymentfc:
    image: your-registry.com/go-commerce-paymentfc:latest
    container_name: go-commerce-paymentfc
    ports:
      - "8083:8083"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=user
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=admin
    depends_on:
      - postgres
      - redis
    networks:
      - go-commerce-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  go-commerce-network:
    driver: bridge
