apiVersion: v1
kind: Secret
metadata:
  name: orderfc-secret
  namespace: go-commerce
  labels:
    app.kubernetes.io/name: orderfc
    app.kubernetes.io/part-of: go-commerce
type: Opaque
stringData:
  db-password: admin
  redis-password: admin
  jwt-secret: secret301
