apiVersion: v1
kind: ConfigMap
metadata:
  name: paymentfc-config
  namespace: go-commerce
  labels:
    app.kubernetes.io/name: paymentfc
    app.kubernetes.io/part-of: go-commerce
data:
  config.yaml: |
    app:
      port: 28083

    database:
      host: postgres-payment
      port: 5432
      user: admin
      password: admin
      name: payment

    redis:
      host: redis
      port: 6379
      password: admin

    kafka:
      broker: kafka:9092
      topics:
        - order.created: order.created
        - payment.success: payment.success
      group_id: payment-service

    xendit:
      secret_api_key: ""
      webhook_token: ""

    mongo:
      uri: mongodb://admin:admin@mongodb:27017
      database: payment_audit

    toggle:
      disable_create_invoice_directly: true

    grpc:
      user_service_addr: userfc:50051
      credentials: ""

    vault:
      host: ""
      token: ""
      path: paymentfc

    tracing:
      endpoint: jaeger:4318
      service_name: paymentfc
      enabled: false
