apiVersion: v1
kind: ConfigMap
metadata:
  name: productfc-config
  namespace: go-commerce
  labels:
    app.kubernetes.io/name: productfc
    app.kubernetes.io/part-of: go-commerce
data:
  config.yaml: |
    app:
      port: 8081

    database:
      host: postgres-product
      port: 5432
      user: admin
      password: admin
      name: product

    redis:
      host: redis
      port: 6379
      password: admin

    secret:
      jwt_secret: secret301

    tracing:
      endpoint: jaeger:4318
      service_name: productfc
      enabled: false
